<?php
// Generated by ZF2's ./bin/classmap_generator.php @ Sun, 15 Jan 2012 19:44:21 -0700
return array(
    'ZfcUserDoctrineCouchODM\Module'                            => __DIR__ . '/Module.php',
    'ZfcUserDoctrineCouchODM\Document\User'                     => __DIR__ . '/src/ZfcUserDoctrineCouchODM/Document/User.php',
    'ZfcUserDoctrineCouchODM\Document\UserMappedSuperClass'     => __DIR__ . '/src/ZfcUserDoctrineCouchODM/Document/UserMappedSuperClass.php',
    'ZfcUserDoctrineCouchODM\Event\ResolveTargetEntityListener' => __DIR__ . '/src/ZfcUserDoctrineCouchODM/Event/ResolveTargetEntityListener.php',
    'ZfcUserDoctrineCouchODM\Mapper\UserCouchDb'                => __DIR__ . '/src/ZfcUserDoctrineCouchODM/Mapper/UserCouchDb.php',
    'ZfcUserDoctrineCouchODM\Options\ModuleOptions'             => __DIR__ . '/src/ZfcUserDoctrineCouchODM/Options/ModuleOptions.php'
);